aws_region = "ap-south-1"
vpc_cidr = "30.1.0.0/16"
public_subnet1_cidr = "30.1.1.0/28"
public_subnet2_cidr = "30.1.2.0/28"
private_subnet_cidr = "30.1.20.0/24"
vpc_name = "Developement"
IGW_name = "tf-igw"
public_subnet1_name = "TS1"
public_subnet2_name = "TS2"
private_subnet_name = "TPS1"
Main_Routing_Table = "Main_Routing_Table"
Private_Routing_Table = "Private_Routing_Table"
key_name = "LaptopKey"
environment = "dev"

